name: CreditsLib
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: jr <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
  RenderingLib:
      git: git://github.com/FarragoFiction/RenderingLib.git
  DollLibCorrect:
      git:  git://github.com/FarragoFiction/DollLibCorrect.git