name: CreditsLib
description: A starting point for Dart libraries or applications.
version: 2.8.0
homepage: https://github.com/FarragoFiction/CharacterLib
author: jadedResearcher, paradoxLands

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
    DollLibCorrect:
      git: git://github.com/FarragoFiction/DollLibCorrect.git
    CommonLib:
      git: git://github.com/FarragoFiction/CommonLib.git
    RenderingLib:
      git: git://github.com/FarragoFiction/RenderingLib.git

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  test: any
