name: CreditsLib
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: jr <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
    DollLibCorrect:
      git:
        url: git://github.com/FarragoFiction/DollLibCorrect.git
        ref: Dart-2.2.0
    CommonLib:
      git:
        url: git://github.com/FarragoFiction/CommonLib.git
        ref: Dart-2.2.0
    RenderingLib:
      git:
        url: git://github.com/FarragoFiction/RenderingLib.git
        ref: Dart-2.2.0

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
